version: "3.8"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"        